---
execution:
  scenario:
    script: ./apache-jmeter/plan/hn-test-plan-taurus.jmx
  concurrency: 15
  ramp-up: 5s
  hold-for: 10m
modules:
  jmeter:
    properties:
      https.use.cached.ssl.context: false
  blazemeter:
    browser-open: false
    token: 5596978ab1bcf62c788f
  console:
    disable: true
  consolidator:
    generalize-labels: false
reporting:
  - module: blazemeter
    test: HydraNorth Load Testing
  - module: console
  - module: junit-xml
    filename: ./junit.xml
    data-source: pass-fail
  - module: fail-criteria
    criterias:
    - avg-rt>120s for 30s, continue as failed
    - fail>10% for 10s, continue as failed
