---
execution:
  scenario:
    script: ./apache-jmeter/plan/hn-test-plan-taurus.jmx
  concurrency: 5
  ramp-up: 5s
  iterations: 3
modules:
  blazemeter:
    browser-open: false
    token: 53669adc226f75ba341e
  console:
    disable: true
  consolidator:
    generalize-labels: false
reporting:
  - module: blazemeter
    test: HydraNorth Load Testing
  - module: console
  - module: junit-xml
    filename: ./junit.xml
    data-source: pass-fail
  - module: fail-criteria
    criterias:
    - avg-rt>120s for 30s, continue as failed
    - fail>10% for 10s, continue as failed
